### ISSUE TITLE
你好,这是完整的代码,是不是有什么没有提交?

### ISSUE THREAD

**Issue by wenjiangit** [Coding/Mart-Android#2]
比如一些自动生成的代码没有生成成功

    @Click
    void login() {
        umengEvent(UmengEvent.ACTION, "欢迎页 _ 登录码市");
        LoginActivity_.intent(this).startForResult(RESULT_LOGIN);
    }

**Comment by cxc2014** [comment]
build 会自动生成，了解下 [AA](https://github.com/androidannotations/androidannotations/wiki)
